import React from 'react';
import { motion } from 'framer-motion';
import { 
  FileText, 
  Download, 
  FileJson, 
  FileSpreadsheet, 
  CheckCircle2, 
  XCircle, 
  MinusCircle,
  TrendingUp,
  Clock,
  Tag
} from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { SentimentResult, calculateSummary, exportToCSV, exportToJSON } from '@/lib/sentimentAnalyzer';
import { jsPDF } from 'jspdf';

interface FullReportProps {
  result: SentimentResult;
}

export const FullReport: React.FC<FullReportProps> = ({ result }) => {
  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleExportCSV = () => {
    const csv = exportToCSV([result]);
    downloadFile(csv, `opinionme-report-${result.id}.csv`, 'text/csv');
  };

  const handleExportJSON = () => {
    const json = exportToJSON([result]);
    downloadFile(json, `opinionme-report-${result.id}.json`, 'application/json');
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    
    // Header with brand
    doc.setFontSize(24);
    doc.setTextColor(59, 130, 246);
    doc.text('OpinionMe', 20, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Powered by AI Syndicate', 20, 28);
    
    // Title
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Sentiment Analysis Report', 20, 45);
    
    // Timestamp
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 52);
    doc.text(`Report ID: ${result.id}`, 20, 58);
    
    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 65, 190, 65);
    
    // Sentiment Result
    const colors: Record<string, [number, number, number]> = {
      positive: [34, 197, 94],
      negative: [239, 68, 68],
      neutral: [234, 179, 8],
    };
    
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Sentiment Classification', 20, 80);
    
    doc.setFontSize(20);
    doc.setTextColor(...colors[result.label]);
    doc.text(result.label.toUpperCase(), 20, 92);
    
    doc.setFontSize(12);
    doc.setTextColor(128, 128, 128);
    doc.text(`Confidence: ${(result.confidence * 100).toFixed(1)}%`, 20, 100);
    
    // Score breakdown
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Score Breakdown', 20, 120);
    
    doc.setFontSize(11);
    doc.setTextColor(...colors.positive);
    doc.text(`Positive: ${(result.scores.positive * 100).toFixed(1)}%`, 25, 130);
    doc.setTextColor(...colors.negative);
    doc.text(`Negative: ${(result.scores.negative * 100).toFixed(1)}%`, 25, 138);
    doc.setTextColor(...colors.neutral);
    doc.text(`Neutral: ${(result.scores.neutral * 100).toFixed(1)}%`, 25, 146);
    
    // Keywords
    if (result.keywords.length > 0) {
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('Key Sentiment Drivers', 20, 165);
      
      doc.setFontSize(10);
      result.keywords.forEach((keyword, index) => {
        doc.setTextColor(...colors[keyword.sentiment]);
        doc.text(`• ${keyword.word} (${keyword.sentiment})`, 25, 175 + (index * 7));
      });
    }
    
    // Analyzed Text
    const textY = result.keywords.length > 0 ? 175 + (result.keywords.length * 7) + 15 : 165;
    
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Analyzed Text', 20, textY);
    
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const textLines = doc.splitTextToSize(result.text, 170);
    doc.text(textLines, 20, textY + 10);
    
    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by OpinionMe - AI Syndicate', 20, pageHeight - 15);
    doc.text('Analysis runs locally using Hugging Face Transformers', 20, pageHeight - 10);
    
    doc.save(`opinionme-report-${result.id}.pdf`);
  };

  const getSentimentIcon = () => {
    switch (result.label) {
      case 'positive':
        return <CheckCircle2 className="w-6 h-6 text-emerald-400" />;
      case 'negative':
        return <XCircle className="w-6 h-6 text-rose-400" />;
      default:
        return <MinusCircle className="w-6 h-6 text-amber-400" />;
    }
  };

  const getSentimentColor = () => {
    switch (result.label) {
      case 'positive':
        return 'text-emerald-400';
      case 'negative':
        return 'text-rose-400';
      default:
        return 'text-amber-400';
    }
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="ghost" size="sm" className="gap-1 text-xs">
          <FileText className="w-3 h-3" />
          Full Report
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[85vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            Full Analysis Report
          </DialogTitle>
          <DialogDescription>
            Complete sentiment analysis details for this text
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="max-h-[60vh] pr-4">
          <div className="space-y-6 py-4">
            {/* Sentiment Result */}
            <motion.div
              className="p-4 rounded-lg bg-muted/50"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <div className="flex items-center gap-3 mb-3">
                {getSentimentIcon()}
                <div>
                  <h4 className="font-semibold">Sentiment Classification</h4>
                  <p className={`text-2xl font-bold ${getSentimentColor()}`}>
                    {result.label.charAt(0).toUpperCase() + result.label.slice(1)}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <TrendingUp className="w-4 h-4" />
                <span>Confidence: <span className="font-medium text-foreground">{(result.confidence * 100).toFixed(1)}%</span></span>
              </div>
            </motion.div>

            {/* Score Breakdown */}
            <motion.div
              className="p-4 rounded-lg bg-muted/50"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
            >
              <h4 className="font-semibold mb-3">Score Breakdown</h4>
              <div className="space-y-3">
                {[
                  { label: 'Positive', score: result.scores.positive, color: 'bg-emerald-500' },
                  { label: 'Negative', score: result.scores.negative, color: 'bg-rose-500' },
                  { label: 'Neutral', score: result.scores.neutral, color: 'bg-amber-500' },
                ].map((item) => (
                  <div key={item.label}>
                    <div className="flex justify-between text-sm mb-1">
                      <span>{item.label}</span>
                      <span className="font-medium">{(item.score * 100).toFixed(1)}%</span>
                    </div>
                    <div className="h-2 bg-muted rounded-full overflow-hidden">
                      <motion.div
                        className={`h-full ${item.color}`}
                        initial={{ width: 0 }}
                        animate={{ width: `${item.score * 100}%` }}
                        transition={{ duration: 0.5, delay: 0.2 }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>

            {/* Keywords */}
            {result.keywords.length > 0 && (
              <motion.div
                className="p-4 rounded-lg bg-muted/50"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
              >
                <div className="flex items-center gap-2 mb-3">
                  <Tag className="w-4 h-4 text-primary" />
                  <h4 className="font-semibold">Key Sentiment Drivers</h4>
                </div>
                <div className="flex flex-wrap gap-2">
                  {result.keywords.map((keyword) => (
                    <span
                      key={keyword.word}
                      className={`px-3 py-1 rounded-full text-sm ${
                        keyword.sentiment === 'positive'
                          ? 'bg-emerald-500/20 text-emerald-400'
                          : keyword.sentiment === 'negative'
                          ? 'bg-rose-500/20 text-rose-400'
                          : 'bg-amber-500/20 text-amber-400'
                      }`}
                    >
                      {keyword.word}
                    </span>
                  ))}
                </div>
              </motion.div>
            )}

            {/* Analyzed Text */}
            <motion.div
              className="p-4 rounded-lg bg-muted/50"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
            >
              <h4 className="font-semibold mb-2">Analyzed Text</h4>
              <p className="text-sm text-muted-foreground whitespace-pre-wrap">{result.text}</p>
            </motion.div>

            {/* Timestamp */}
            <motion.div
              className="flex items-center gap-2 text-sm text-muted-foreground"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4 }}
            >
              <Clock className="w-4 h-4" />
              <span>Analyzed: {result.timestamp.toLocaleString()}</span>
            </motion.div>
          </div>
        </ScrollArea>

        {/* Export buttons */}
        <div className="flex flex-wrap gap-2 pt-4 border-t border-border">
          <Button variant="outline" size="sm" onClick={handleExportPDF} className="gap-2">
            <FileText className="w-4 h-4 text-rose-400" />
            Download PDF
          </Button>
          <Button variant="outline" size="sm" onClick={handleExportCSV} className="gap-2">
            <FileSpreadsheet className="w-4 h-4 text-emerald-400" />
            Download CSV
          </Button>
          <Button variant="outline" size="sm" onClick={handleExportJSON} className="gap-2">
            <FileJson className="w-4 h-4 text-amber-400" />
            Download JSON
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};
